// export * from './user'
export * as authValidation from './auth'
export * as variantValidation from './variant'
export * as productValidation from './product'
export * as catlogueValidation from './catlogue'
export * as roleValidation from './role'
export * as userValidation from './user'
export * as agencyValidation from './agency'
export * as tabmasterValidation from './tabmaster'
export * as filterValidation from './filter'
export * as galleryValidation from './gallery'